# logging 레벨 설정
logging:
  level:
    root: INFO
    sql: INFO
# Overloaded POST 사용
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
# session
server:
  port: 8080
  servlet:
    session:
      timeout: 10m # 기본이 30분이고 최소는 1분입니다.
mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #config-location: classpath:mybatis-config.xml